#!/usr/bin/env bash
set -euo pipefail

# bundle.sh — Generates a single-file distributable of shellia
#
# Usage: ./bundle.sh [output_path]
#
# Concatenates all library modules, embeds default data files, inlines tool
# definitions, and appends the entrypoint logic into one portable bash script.
# The source tree remains untouched — this only writes to the output file.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-${SCRIPT_DIR}/dist/shellia}"

mkdir -p "$(dirname "$OUTPUT")"

# --- Helpers ---

# Strip the shebang line and "set -euo pipefail" from library files
strip_header() {
    sed -E '
        /^#!\/usr\/bin\/env bash$/d
        /^#!\/bin\/bash$/d
        /^set -euo pipefail$/d
    '
}

# Patch a library file during inclusion (pipe filter)
# Applies source-specific transformations inline
patch_file() {
    local mod="$1"
    case "$mod" in
        lib/prompt.sh)
            # Replace: base_prompt=$(cat "${SHELLIA_DIR}/defaults/system_prompt.txt")
            # With:    base_prompt=$(_shellia_default_system_prompt)
            sed 's|base_prompt=$(cat "${SHELLIA_DIR}/defaults/system_prompt.txt")|base_prompt=$(_shellia_default_system_prompt)|'
            ;;
        lib/executor.sh)
            # Replace the entire load_dangerous_commands function with a
            # bundle-aware version that uses embedded defaults as fallback
            awk '
                /^load_dangerous_commands\(\) \{/ {
                    print "load_dangerous_commands() {"
                    print "    DANGEROUS_PATTERNS=()"
                    print "    local danger_file=\"${SHELLIA_DANGEROUS_FILE:-}\""
                    print ""
                    print "    if [[ -n \"$danger_file\" && -f \"$danger_file\" ]]; then"
                    print "        # User has a custom dangerous_commands file"
                    print "        while IFS= read -r pattern; do"
                    print "            [[ -z \"$pattern\" ]] && continue"
                    print "            [[ \"$pattern\" =~ ^[[:space:]]*# ]] && continue"
                    print "            DANGEROUS_PATTERNS+=(\"$pattern\")"
                    print "        done < \"$danger_file\""
                    print "    else"
                    print "        # Bundle mode: use embedded defaults"
                    print "        while IFS= read -r pattern; do"
                    print "            [[ -z \"$pattern\" ]] && continue"
                    print "            [[ \"$pattern\" =~ ^[[:space:]]*# ]] && continue"
                    print "            DANGEROUS_PATTERNS+=(\"$pattern\")"
                    print "        done <<< \"$(_shellia_default_dangerous_commands)\""
                    print "    fi"
                    print "}"
                    # Skip the original function body
                    skip = 1
                    brace_depth = 1
                    next
                }
                skip && /\{/ { brace_depth++ }
                skip && /\}/ {
                    brace_depth--
                    if (brace_depth == 0) { skip = 0; next }
                }
                !skip { print }
            '
            ;;
        lib/config.sh)
            # Replace: cp "${SHELLIA_DIR}/defaults/dangerous_commands" "$SHELLIA_DANGEROUS_FILE"
            # With:    _shellia_default_dangerous_commands > "$SHELLIA_DANGEROUS_FILE"
            sed 's|cp "${SHELLIA_DIR}/defaults/dangerous_commands" "$SHELLIA_DANGEROUS_FILE"|_shellia_default_dangerous_commands > "$SHELLIA_DANGEROUS_FILE"|'
            ;;
        lib/tools.sh)
            # Replace load_tools() with a no-op (tools are inlined in the bundle)
            awk '
                /^load_tools\(\) \{/ {
                    print "load_tools() {"
                    print "    # Bundle mode: tools are inlined, nothing to source"
                    print "    debug_log \"tools\" \"bundle mode - tools already loaded\""
                    print "}"
                    skip = 1
                    brace_depth = 1
                    next
                }
                skip && /\{/ { brace_depth++ }
                skip && /\}/ {
                    brace_depth--
                    if (brace_depth == 0) { skip = 0; next }
                }
                !skip { print }
            '
            ;;
        *)
            # No patches needed
            cat
            ;;
    esac
}

# --- Build the bundle ---

{
    # 1. Shebang and top-level settings
    cat <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# shellia — single-file bundle
# Generated by bundle.sh — do not edit directly
# =============================================================================

HEADER

    # 2. Embedded default data files
    cat <<'EMBED_SECTION'
# --- Embedded defaults (replacing defaults/ directory) ---

EMBED_SECTION

    # Embed system_prompt.txt as a function
    echo '_shellia_default_system_prompt() {'
    echo "    cat <<'SYSTEM_PROMPT_EOF'"
    cat "${SCRIPT_DIR}/defaults/system_prompt.txt"
    echo ''  # ensure newline after file content
    echo 'SYSTEM_PROMPT_EOF'
    echo '}'
    echo ''

    # Embed dangerous_commands as a function
    echo '_shellia_default_dangerous_commands() {'
    echo "    cat <<'DANGEROUS_COMMANDS_EOF'"
    cat "${SCRIPT_DIR}/defaults/dangerous_commands"
    echo ''  # ensure newline after file content
    echo 'DANGEROUS_COMMANDS_EOF'
    echo '}'
    echo ''

    # 3. Library modules in source order (with inline patching)
    modules=(
        "lib/utils.sh"
        "lib/config.sh"
        "lib/profiles.sh"
        "lib/prompt.sh"
        "lib/api.sh"
        "lib/executor.sh"
        "lib/themes.sh"
        "lib/tools.sh"
    )

    for mod in "${modules[@]}"; do
        echo "# ============================================================================="
        echo "# ${mod}"
        echo "# ============================================================================="
        echo ""
        cat "${SCRIPT_DIR}/${mod}" | strip_header | patch_file "$mod"
        echo ""
    done

    # 4. Tool definitions (inlined — replaces dynamic load_tools discovery)
tool_files=(
    "lib/tools/run_command.sh"
    "lib/tools/run_plan.sh"
    "lib/tools/ask_user.sh"
    "lib/tools/delegate_task.sh"
    "lib/tools/todo_write.sh"
)

    for tool in "${tool_files[@]}"; do
        echo "# ============================================================================="
        echo "# ${tool}"
        echo "# ============================================================================="
        echo ""
        cat "${SCRIPT_DIR}/${tool}" | strip_header
        echo ""
    done

    # 5. Entrypoint (from the main shellia script, after the source/setup lines)
    echo "# ============================================================================="
    echo "# Entrypoint"
    echo "# ============================================================================="
    echo ""

    # Extract everything from "# Check dependencies" onward
    sed -n '/^# Check dependencies$/,$ p' "${SCRIPT_DIR}/shellia"

} > "$OUTPUT"

chmod +x "$OUTPUT"

# --- Verification ---
LINE_COUNT=$(wc -l < "$OUTPUT" | tr -d ' ')
SIZE=$(wc -c < "$OUTPUT" | tr -d ' ')

echo "Bundle created: ${OUTPUT}"
echo "  Lines: ${LINE_COUNT}"
echo "  Size:  ${SIZE} bytes"
echo ""

# Quick syntax check
if bash -n "$OUTPUT" 2>/dev/null; then
    echo "Syntax check: PASSED"
else
    echo "Syntax check: FAILED"
    bash -n "$OUTPUT"
    exit 1
fi

echo ""
echo "Test with: ${OUTPUT} --version"
